version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs:ro
    ports:
      - "443:443"
    depends_on:
      - web
